# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afabac7708a7965a02624020d0f9a58d82904fbc4aa3beac83415948f4f2eb9f77ec3f07728bd2b0c8fb8fa73b029e9a464d07011c3bf8e43b2366a74decd832

test:
  secret_key_base: ab7684a9cdc79d855254285d2c9acbab68144df9bfe69f9bc3bed0d3f6f8c403fab63711f9a33eb3751e7727d87ee1e9dcc9df62abf3508e71c6bfdd29f9618b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
